// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASeTyMe91NsN9BWcOE5nFnk3e-CS2t_nE',
    appId: '1:851734895600:web:c0d6d2a0d60b04e8b8db35',
    messagingSenderId: '851734895600',
    projectId: 'dreamapp-1872c',
    authDomain: 'dreamapp-1872c.firebaseapp.com',
    storageBucket: 'dreamapp-1872c.appspot.com',
    measurementId: 'G-ESVFSGHVN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeRqylYYAaUW2_lD9zWibPd2375r1lh9c',
    appId: '1:851734895600:android:df76107564a15920b8db35',
    messagingSenderId: '851734895600',
    projectId: 'dreamapp-1872c',
    storageBucket: 'dreamapp-1872c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgiuxgv5bQAT8CSKtzetaNCzeolP9r58U',
    appId: '1:851734895600:ios:a6cd8a6e291c9358b8db35',
    messagingSenderId: '851734895600',
    projectId: 'dreamapp-1872c',
    storageBucket: 'dreamapp-1872c.appspot.com',
    iosClientId: '851734895600-elg2d1go283l8b6toipv9jchqhhvadq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.notebookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgiuxgv5bQAT8CSKtzetaNCzeolP9r58U',
    appId: '1:851734895600:ios:a6cd8a6e291c9358b8db35',
    messagingSenderId: '851734895600',
    projectId: 'dreamapp-1872c',
    storageBucket: 'dreamapp-1872c.appspot.com',
    iosClientId: '851734895600-elg2d1go283l8b6toipv9jchqhhvadq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.notebookApp',
  );
}
